apiVersion: apps/v1
kind: Deployment
metadata:
  name: eth-proxy-deployment
  labels:
    app: eth-proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eth-proxy
  template:
    metadata:
      labels:
        app: eth-proxy
    spec:
      containers:
        - name: eth-proxy-container
          image: luishsoares/eth-proxy:latest
          ports:
            - containerPort: 8088