apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: custom-routing-behavior
route:
  strip_path: true
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: test-consumer
username: "test-consumer"
credentials:
  - api-key-secret
---
apiVersion: configuration.konghq.com/v1
kind: KongCredential
metadata:
  name: test-consumer-key
consumerRef: test-consumer
type: key-auth
config:
  keyFrom:
    secretKeyRef:
      name: api-key-secret
      key: key